In [1]:
import pandas as pd
import numpy as np



In [2]:
data = pd.read_csv('/Users/saitejasriyerramsetti/Documents/BDA 696/Final Project/Crimes_-_2001_to_Present_20240918.csv')

In [5]:
data.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [4]:
data.head()# IUCR illinois code for reporting crimes

ID Case Number                    Date                 Block  IUCR  \
0  11037294    JA371270  03/18/2015 12:00:00 PM     0000X W WACKER DR  1153   
1  11646293    JC213749  12/20/2018 03:00:00 PM  023XX N LOCKWOOD AVE  1154   
2  11645836    JC212333  05/01/2016 12:25:00 AM   055XX S ROCKWELL ST  1153   
3  11645959    JC211511  12/20/2018 04:00:00 PM    045XX N ALBANY AVE  2820   
4  11645601    JC212935  06/01/2014 12:01:00 AM   087XX S SANGAMON ST  1153   

         Primary Type                              Description  \
0  DECEPTIVE PRACTICE      FINANCIAL IDENTITY THEFT OVER $ 300   
1  DECEPTIVE PRACTICE  FINANCIAL IDENTITY THEFT $300 AND UNDER   
2  DECEPTIVE PRACTICE      FINANCIAL IDENTITY THEFT OVER $ 300   
3       OTHER OFFENSE                         TELEPHONE THREAT   
4  DECEPTIVE PRACTICE      FINANCIAL IDENTITY THEFT OVER $ 300   

  Location Description  Arrest  Domestic  ...  Ward  Community Area  FBI Code  \
0                 BANK   False     False  ...  42.0            32.0        11   
1            APARTMENT   False     False  ...  36.0            19.0        11   
2                  NaN   False     False  ...  15.0            63.0        11   
3            RESIDENCE   False     False  ...  33.0            14.0       08A   
4            RESIDENCE   False     False  ...  21.0            71.0        11   

   X Coordinate Y Coordinate  Year              Updated On  Latitude  \
0           NaN          NaN  2015  08/01/2017 03:52:26 PM       NaN   
1           NaN          NaN  2018  04/06/2019 04:04:43 PM       NaN   
2           NaN          NaN  2016  04/06/2019 04:04:43 PM       NaN   
3           NaN          NaN  2018  04/06/2019 04:04:43 PM       NaN   
4           NaN          NaN  2014  04/06/2019 04:04:43 PM       NaN   

  Longitude  Location  
0       NaN       NaN  
1       NaN       NaN  
2       NaN       NaN  
3       NaN       NaN  
4       NaN       NaN  

[5 rows x 22 columns]

In [6]:
data['Beat'].head()

0     111
1    2515
2     824
3    1724
4    2222
Name: Beat, dtype: int64

In [9]:
data.shape #8156508, 22

(8156508, 22)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8156508 entries, 0 to 8156507
Data columns (total 22 columns):
 #   Column                Dtype  
---  ------                -----  
 0   ID                    int64  
 1   Case Number           object 
 2   Date                  object 
 3   Block                 object 
 4   IUCR                  object 
 5   Primary Type          object 
 6   Description           object 
 7   Location Description  object 
 8   Arrest                bool   
 9   Domestic              bool   
 10  Beat                  int64  
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object 
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64  
 18  Updated On            object 
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object 
dtypes: bool(2), float64(7), int64(3), object(1

In [11]:
data.describe

<bound method NDFrame.describe of                ID Case Number                    Date  \
0        11037294    JA371270  03/18/2015 12:00:00 PM   
1        11646293    JC213749  12/20/2018 03:00:00 PM   
2        11645836    JC212333  05/01/2016 12:25:00 AM   
3        11645959    JC211511  12/20/2018 04:00:00 PM   
4        11645601    JC212935  06/01/2014 12:01:00 AM   
...           ...         ...                     ...   
8156503  12131776    JD327752  08/10/2020 08:30:00 PM   
8156504  12082414    JD269218  06/18/2020 09:00:00 PM   
8156505  12118237    JD311791  07/27/2020 03:02:00 PM   
8156506  12142591    JD340297  08/14/2020 03:00:00 PM   
8156507  12002171    JD177406  03/06/2020 02:00:00 PM   

                                       Block  IUCR         Primary Type  \
0                          0000X W WACKER DR  1153   DECEPTIVE PRACTICE   
1                       023XX N LOCKWOOD AVE  1154   DECEPTIVE PRACTICE   
2                        055XX S ROCKWELL ST  1153   DEC

In [12]:
data.isnull().sum()

ID                           0
Case Number                  0
Date                         0
Block                        0
IUCR                         0
Primary Type                 0
Description                  0
Location Description     13553
Arrest                       0
Domestic                     0
Beat                         0
District                    47
Ward                    614829
Community Area          613453
FBI Code                     0
X Coordinate             89841
Y Coordinate             89841
Year                         0
Updated On                   0
Latitude                 89841
Longitude                89841
Location                 89841
dtype: int64

In [13]:
data['Community Area'].value_counts()

Community Area
25.0    466393
8.0     268844
43.0    248599
23.0    234114
28.0    232038
         ...  
74.0     16871
12.0     14095
47.0     11205
9.0       7553
0.0         76
Name: count, Length: 78, dtype: int64

In [14]:
data['Location'].unique()

array([nan, '(41.830481843, -87.621751752)',
       '(41.836310224, -87.639624112)', ...,
       '(41.873179092, -87.718078907)', '(41.70228413, -87.606300025)',
       '(41.725697102, -87.605186246)'], dtype=object)

In [15]:
data['X Coordinate'].unique()

array([     nan, 1178180., 1173292., ..., 1129047., 1203643., 1121084.])

In [16]:
data['Latitude'].unique()

array([        nan, 41.83048184, 41.83631022, ..., 41.87317909,
       41.70228413, 41.7256971 ])

In [17]:
data['Primary Type'].unique()

array(['DECEPTIVE PRACTICE', 'OTHER OFFENSE', 'THEFT', 'BATTERY',
       'ASSAULT', 'WEAPONS VIOLATION', 'INTERFERENCE WITH PUBLIC OFFICER',
       'SEX OFFENSE', 'BURGLARY', 'NARCOTICS', 'LIQUOR LAW VIOLATION',
       'CRIM SEXUAL ASSAULT', 'MOTOR VEHICLE THEFT', 'CRIMINAL DAMAGE',
       'OFFENSE INVOLVING CHILDREN', 'CRIMINAL TRESPASS', 'ROBBERY',
       'PUBLIC PEACE VIOLATION', 'CRIMINAL SEXUAL ASSAULT',
       'PROSTITUTION', 'STALKING', 'HOMICIDE', 'KIDNAPPING', 'ARSON',
       'CONCEALED CARRY LICENSE VIOLATION', 'GAMBLING', 'OBSCENITY',
       'INTIMIDATION', 'OTHER NARCOTIC VIOLATION', 'PUBLIC INDECENCY',
       'NON-CRIMINAL', 'HUMAN TRAFFICKING', 'RITUALISM',
       'DOMESTIC VIOLENCE', 'NON-CRIMINAL (SUBJECT SPECIFIED)',
       'NON - CRIMINAL'], dtype=object)

In [22]:
data['Domestic'].value_counts()

Domestic
False    6752861
True     1403647
Name: count, dtype: int64

In [23]:
data['District'].value_counts()

District
8.0     547438
11.0    520147
6.0     476966
7.0     465611
25.0    462450
4.0     462297
3.0     413535
12.0    408274
9.0     396915
2.0     387357
19.0    369432
18.0    368329
5.0     359942
10.0    350902
15.0    345793
1.0     335478
14.0    314830
16.0    274085
22.0    266608
24.0    248332
17.0    235862
20.0    145616
31.0       258
21.0         4
Name: count, dtype: int64